# Generated by Django 5.0.4 on 2024-05-15 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('ucid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content_pretty_name', models.CharField(max_length=100)),
                ('content_kind', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard'), ('Unset', 'Unset')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('learning_stage', models.CharField(choices=[('Elementary', 'Elementary'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('level1_id', models.CharField(max_length=100)),
                ('level2_id', models.CharField(max_length=100)),
                ('level3_id', models.CharField(max_length=100)),
                ('level4_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('ucid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content_pretty_name', models.CharField(max_length=100)),
                ('content_kind', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard'), ('Unset', 'Unset')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('learning_stage', models.CharField(choices=[('Elementary', 'Elementary'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('level1_id', models.CharField(max_length=100)),
                ('level2_id', models.CharField(max_length=100)),
                ('level3_id', models.CharField(max_length=100)),
                ('level4_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Unspecified'), ('null', 'Null')], max_length=20)),
                ('points', models.IntegerField()),
                ('badges_cnt', models.IntegerField()),
                ('first_login_date_TW', models.DateTimeField()),
                ('user_grade', models.IntegerField()),
                ('user_city', models.CharField(max_length=100)),
                ('has_teacher_cnt', models.IntegerField()),
                ('is_self_coach', models.BooleanField()),
                ('has_student_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_TW', models.DateTimeField()),
                ('ucid', models.CharField(max_length=100)),
                ('upid', models.CharField(max_length=100)),
                ('problem_number', models.IntegerField()),
                ('exercise_problem_re', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('total_sec_taken', models.IntegerField()),
                ('total_attempt_cnt', models.IntegerField()),
                ('used_hint_cnt', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.student')),
            ],
        ),
    ]
