# Generated by Django 5.0.4 on 2024-06-09 08:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('ucid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content_pretty_name', models.CharField(max_length=100)),
                ('content_kind', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard'), ('Unset', 'Unset')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('learning_stage', models.CharField(choices=[('Elementary', 'Elementary'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('level1_id', models.CharField(max_length=100)),
                ('level2_id', models.CharField(max_length=100)),
                ('level3_id', models.CharField(max_length=100)),
                ('level4_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('ucid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_pretty_name', models.CharField(max_length=100)),
                ('content_kind', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Hard', 'Hard'), ('Unset', 'Unset')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('learning_stage', models.CharField(choices=[('Elementary', 'Elementary'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('level1_id', models.CharField(max_length=100)),
                ('level2_id', models.CharField(max_length=100)),
                ('level3_id', models.CharField(max_length=100)),
                ('level4_id', models.CharField(max_length=100)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.content')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.question')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Unspecified'), ('null', 'Null')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('badges_cnt', models.IntegerField(default=1)),
                ('first_login_date_TW', models.DateTimeField(null=True)),
                ('user_grade', models.IntegerField(default=1)),
                ('user_city', models.CharField(default='', max_length=100)),
                ('has_teacher_cnt', models.IntegerField(default=1)),
                ('is_self_coach', models.BooleanField(default=False)),
                ('has_student_cnt', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExerciseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_TW', models.DateTimeField(default=django.utils.timezone.now)),
                ('upid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('problem_number', models.IntegerField(default=1)),
                ('exercise_problem_repeat_session', models.IntegerField(default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('total_sec_taken', models.IntegerField(default=0)),
                ('total_attempt_cnt', models.IntegerField(default=0)),
                ('used_hint_cnt', models.IntegerField(default=0)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.choice')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.exercise')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.student')),
                ('ucid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.content')),
            ],
        ),
    ]
