# Generated by Django 5.0.4 on 2024-06-14 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseParameters',
            fields=[
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_interaction.exercise')),
                ('difficulty', models.FloatField()),
                ('discrimination', models.FloatField()),
                ('guessing', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='discrimination',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='content',
            name='guessing',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='discrimination',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='guessing',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='content',
            name='difficulty',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='user_interaction.exercise'),
        ),
    ]
