# Generated by Django 5.0.4 on 2024-06-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0002_exerciseparameters_content_discrimination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='ucid',
            field=models.CharField(default=1, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
