# Generated by Django 5.0.4 on 2024-06-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0004_remove_exercise_content_alter_content_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='discrimination',
            field=models.FloatField(default=0.2),
        ),
    ]
