# Generated by Django 5.0.4 on 2024-06-15 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0006_exercise_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='ucid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_interaction.content'),
        ),
    ]
