# Generated by Django 5.0.4 on 2024-06-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0007_alter_studentresponse_ucid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ability',
            field=models.FloatField(default=0),
        ),
    ]
