# Generated by Django 5.0.4 on 2024-07-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0008_student_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_pretty_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_pretty_name_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subject_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subject_zh',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
