# Generated by Django 5.0.4 on 2024-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0008_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
