# Generated by Django 5.0.4 on 2024-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0009_alter_student_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='badges_cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='has_student_cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='has_teacher_cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_self_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_grade',
            field=models.IntegerField(default=1),
        ),
    ]
