# Generated by Django 5.0.4 on 2024-07-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0010_remove_content_content_pretty_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='translated_content_pretty_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
