# Generated by Django 5.0.4 on 2024-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0010_alter_student_badges_cnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
