# Generated by Django 5.0.4 on 2024-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0011_alter_student_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_login_date_TW',
            field=models.DateTimeField(null=True),
        ),
    ]
