# Generated by Django 5.0.4 on 2024-05-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0012_alter_student_first_login_date_tw'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_interaction.question'),
        ),
    ]
