# Generated by Django 5.0.4 on 2024-05-15 11:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0013_studentresponse_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='exercise_problem_re',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='problem_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='timestamp_TW',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='total_sec_taken',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='upid',
            field=models.IntegerField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='used_hint_cnt',
            field=models.IntegerField(default=1),
        ),
    ]
