# Generated by Django 5.0.4 on 2024-05-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0014_alter_studentresponse_exercise_problem_re_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='total_attempt_cnt',
            field=models.IntegerField(default=1),
        ),
    ]
