# Generated by Django 5.0.4 on 2024-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0015_alter_studentresponse_total_attempt_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
