# Generated by Django 5.0.4 on 2024-05-22 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0018_remove_exercise_completed_studentexercisecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='content',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_interaction.content'),
        ),
    ]
