# Generated by Django 5.0.4 on 2024-05-22 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0019_exercise_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interaction.content'),
        ),
    ]
