# Generated by Django 5.0.4 on 2024-05-23 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interaction', '0023_alter_studentresponse_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='choice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_interaction.choice'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_interaction.question'),
        ),
    ]
