# Generated by Django 5.0.4 on 2024-05-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
    ]
